In [13]:
import numpy as np
np1 = np.array([1,2,3,4,5])
print(np1)

[1 2 3 4 5]


shape = length

In [14]:
print(np1.shape)

(5,)


range

In [15]:
np2 = np.arange(5)
print(np2)

[0 1 2 3 4]


step

In [16]:
np3 = np.arange(0, 5, 2)
print(np3)

[0 2 4]


zeros

In [18]:
np4 = np.zeros(10)
print(np4)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


multidimensional zeros

In [21]:
np5 = np.zeros((2, 10))
print(np5)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


full

In [22]:
np6 = np.full((10), 6)
print(np6)

[6 6 6 6 6 6 6 6 6 6]


multidimensional full

In [23]:
np7 = np.full((2, 10), 6)
print(np7)

[[6 6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6 6]]


convert python list to np

In [24]:
my_list = [1,2,3,4,5]
np8 = np.array(my_list)
print(np8)

[1 2 3 4 5]


In [28]:
print(np8[3])

4
