In [1]:
import numpy as np

searching numpy arrays easy ways

In [5]:
np1 = np.array([1,2,3,4,5,6,7,8,9,10,3])
x = np.where(np1 == 3)
print(np1)
print(x)
print(x[0])
print(np1[x[0]])

[ 1  2  3  4  5  6  7  8  9 10  3]
(array([ 2, 10]),)
[ 2 10]
[3 3]


searching even number

In [9]:
y = np.where(np1 % 2 == 0)
print(np1)
print(y)
print(y[0])
print(np1[y[0]])

[ 1  2  3  4  5  6  7  8  9 10  3]
(array([1, 3, 5, 7, 9]),)
[1 3 5 7 9]
[ 2  4  6  8 10]


searching odd numbers

In [11]:
z = np.where(np1 % 2 != 0)
print(np1)
print(np1[z[0]])

[ 1  2  3  4  5  6  7  8  9 10  3]
[1 3 5 7 9 3]
