In [1]:
import numpy as np

filtering numpy arrays with boolean index lists

In [2]:
np1 = np.array([1,2,3,4,5,6,7,8,9,10])
x = [True, True, False, False, False, False, False, False, False, False]
print(np1)
print(x)

[ 1  2  3  4  5  6  7  8  9 10]
[True, True, False, False, False, False, False, False, False, False]


In [5]:
filtered = []
for thing in np1:
    if thing % 2 == 0:
        filtered.append(True)
    else:
        filtered.append(False)
print(np1)
print(filtered)
print(np1[filtered])

[ 1  2  3  4  5  6  7  8  9 10]
[False, True, False, True, False, True, False, True, False, True]
[ 2  4  6  8 10]


shortcut for filter

In [6]:
filtered =  np1 % 2 ==  0
print(np1)
print(filtered)
print(np1[filtered])


[ 1  2  3  4  5  6  7  8  9 10]
[False  True False  True False  True False  True False  True]
[ 2  4  6  8 10]


In [7]:
filtered = np1 > 5
print(np1)
print(filtered)
print(np1[filtered])

[ 1  2  3  4  5  6  7  8  9 10]
[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]
