In [1]:
import numpy as np

numpy universal function

In [2]:
np1 = np.array([-3,-2,-1,0,1,2,3,4,5,6,7,8,9])
print(np1)

[-3 -2 -1  0  1  2  3  4  5  6  7  8  9]


square root of each element

In [3]:
print(np.sqrt(np1))

[       nan        nan        nan 0.         1.         1.41421356
 1.73205081 2.         2.23606798 2.44948974 2.64575131 2.82842712
 3.        ]


C:\Users\USER\AppData\Local\Temp\ipykernel_33620\1705193581.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(np1))


absolute value

In [4]:
print(np.absolute(np1))

[3 2 1 0 1 2 3 4 5 6 7 8 9]


exponentials

In [5]:
print(np.exp(np1))

[4.97870684e-02 1.35335283e-01 3.67879441e-01 1.00000000e+00
 2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03]


min/max

In [6]:
print(np.max(np1))

9


In [7]:
print(np.min(np1))

-3


sign positive or negative

In [8]:
print(np.sign(np1))

[-1 -1 -1  0  1  1  1  1  1  1  1  1  1]


trignometric
sin, cos, log

In [9]:
print(np.sin(np1))

[-0.14112001 -0.90929743 -0.84147098  0.          0.84147098  0.90929743
  0.14112001 -0.7568025  -0.95892427 -0.2794155   0.6569866   0.98935825
  0.41211849]


In [10]:
print(np.log(np1))

[       nan        nan        nan       -inf 0.         0.69314718
 1.09861229 1.38629436 1.60943791 1.79175947 1.94591015 2.07944154
 2.19722458]


C:\Users\USER\AppData\Local\Temp\ipykernel_33620\2460114728.py:1: RuntimeWarning: divide by zero encountered in log
  print(np.log(np1))
C:\Users\USER\AppData\Local\Temp\ipykernel_33620\2460114728.py:1: RuntimeWarning: invalid value encountered in log
  print(np.log(np1))


In [11]:
print(np.tan(np1))

[ 0.14254654  2.18503986 -1.55740772  0.          1.55740772 -2.18503986
 -0.14254654  1.15782128 -3.38051501 -0.29100619  0.87144798 -6.79971146
 -0.45231566]
