In [1]:
import numpy as np

shape and reshape

In [3]:
np1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(np1)
print(np1.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)


create 2-d array and get shape (rows/columns elements)

In [5]:
np2 = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(np2)
print(np2.shape)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
(2, 6)


resahpe 2-d 

In [13]:
np3 = np1.reshape(3,4)
print(np3)
print(np3.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


reshapr 3-d array

In [17]:
np4 = np1.reshape(2,3,2)
print(np4)
print(np4.shape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)


flatten to 1-d

In [19]:
np5 = np4.reshape(-1)
print(np5)
print(np5.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
