In [2]:
import numpy as np


slicing numpy arrays

In [3]:
np1 = np.array([1,2,3,4,5,6,7,8,9])
print(np1)

[1 2 3 4 5 6 7 8 9]


return 2,3,4,5

In [4]:
print(np1[1:5])

[2 3 4 5]


return negative slices

In [5]:
print(np1[-3:-1]) # 7 - 8

[7 8]


steps

In [6]:
print(np1[1:5])

[2 3 4 5]


In [7]:
print(np1[1:5:2])

[2 4]


In [8]:
print(np1[0::2])

[1 3 5 7 9]


slice a 2d-array

In [10]:
np2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(np2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [12]:
print(np2[0,2])

3


In [13]:
print(np2[1,3])

9


In [15]:
print(np2[0:1, 1:3]) # print(np2[rows, columns])

[[2 3]]


In [16]:
print(np2[0:2, 1:3])

[[2 3]
 [7 8]]
