In [1]:
import numpy as np

sorting numpy array

In [3]:
np1 = np.array([3,1,4,0,2,8])
print(np1)
print(np.sort(np1))

[3 1 4 0 2 8]
[0 1 2 3 4 8]


alphabetical

In [4]:
np2 = np.array(["Ramim", "Mojahid", "Jhon", "Alice"])
print(np2)
print(np.sort(np2))

['Ramim' 'Mojahid' 'Jhon' 'Alice']
['Alice' 'Jhon' 'Mojahid' 'Ramim']


boolean

In [5]:
np3 = np.array([True, False, True, False])
print(np3)
print(np.sort(np3))

[ True False  True False]
[False False  True  True]


2-d array sorting

In [6]:
np4 = np.array([[6,3,8,4,1],[9,4,0,1,2]])
print(np4)
print(np.sort(np4))

[[6 3 8 4 1]
 [9 4 0 1 2]]
[[1 3 4 6 8]
 [0 1 2 4 9]]
